### ISSUE TITLE
Design/code Review 1

### ISSUE THREAD

**Issue by potatoesnmolasses** [OscarJohnson6/IndieProject#2]
# Design/Code Review 1

### Reviewer: Jordan Gruel

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Looks good!  The application helps to solve a relatable problem – I hate when fitness trackers are locked behind a paywall.  <br>It needs a name!  Of course, this can come later, but once it has a name (which can always be changed), it automatically feels more polished. <br>In terms of what users would see when looking up the application, it might serve to be a bit more specific about the functionalities you plan to include – of course you mention BMI, but what else?  If a potential user is looking for something specific, it could make or break their interest in the application.  | 
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | I know you said you weren’t a big fan, but I genuinely like the storyboard you have and I think it’s quite useful to walk through the website design, and easy to understand! <br> I can extrapolate from what you currently have, but it would be nice to have one example of a new entry update (for an existing user/account).<br>Also, what might the Exercises page look like, what entry options might the form have, and how would those results look, approximately?  We went over that when we discussed your project, but for future projects it would be helpful to see those represented!| 
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|   If I recall, you were creating a database with the various data metrics each in a one-to-many relationship with the User table.  This meets the requirement for at least one one-to-many relationship and keeps the classes from getting too long. <br> Could it be worth it to combine any of the classes implementing the Identity interface? Each take a date based off when they’re entered, but you could specify within the instance variables.  Just a thought! <br> If you do end up adding the features described in your v2, where the user can save their favorite exercises, do you plan to add another database table/dao for the exercises?|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  7. No sensitive information is visible in the repository (secrets, passwords, etc). |  This looks excellent!  You’re already pretty deep into the process of incorporating your apis.  I haven’t done that yet, so can’t provide feedback, but great work!<br>While none of your classes are overly long, you do have quite a few of them, many of which utilize similar data (a date and the entered metric).  I mentioned above, but you could eliminate some of the copy-paste code by consolidating the classes.  <br>If you get a chance, it might be worth checking out Project Lombok to clean up some of your workspace – but not a necessity for sure. <br>We didn’t discuss unit testing too much, but do you intend to create tests for each metric (I see you have one for height, but how about for the others)?

Great work so far and good luck moving forward!!

**Comment by pawaitemadisoncollege** [comment]
Hi @potatoesnmolasses! Thank you for your thoughtful review of @OscarJohnson6 's project so far. It's clear you put in some good time and thought into your work here. You clearly documented what looks good so far and identified actionable areas for improvement. @OscarJohnson6 ChatGPT might be helpful for creating some name options if you need help!
